language: perl
perl:
  - "5.8"
  - "5.12"
  - "5.16"
  - "5.20"
  - "5.24"

before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - prove -r xt
  - perl Build.PL && ./Build build
  - cover -test

after_success:
  - cover -report codecov

notifications:
  slack:
    - secure: "PY7tMhHBvL/k+gPGlrcoEqnqLw4NtxZrYQ2Slah97+fVeoOHhnpyJhGVgTik7bko8uLA8U84ZfxNn4GEXUDmF1cthgV8KIUla/f/279jIASPRtB0t28ORt0cGeGbAMg6n+q4962JqU9krnLscgC7YDXdBZrgA4c1BvO/sW55F+oJKdW7tyP91EtJBmvkUE6bj8lIa6Ey4wNsp7Z0p8bBkbH3sPRKNWWkqLvXMZ7xGkBWMAATgrwjyqQCfTQuZJnbScDHK65wcXwW+3muEfhpEE0pWpcU60BtkC0/r0HDfMYo+h7Pqe7kfKabMLkiEa7r3wBUJkhj6OvAQMgj3XbBL/ivfJg69gASD4AO5vgF8AeJTgssuuxc31jDgXkFRz6JYPsy6RLhLcZBGAN7bEhmrAmN9dLmTNUHNNcP8Ii5OnyrmqZs7SorUHzIwBPNJ5QVv80Z3ul52lrQgn+nHQzE79QAbk25dNUyP2ryTO7zgFz1wolkFgAqwIP4AbsOW3sWzq4S1tJUZkfPY4Zqg9dF4zonq+vRtQSzLj3lM7Bblh1hidVXqDu/ISD9FoHqS67IRMG7gD2cweqsvp9XjCxMZXpDGDYsYPqhKxXQay6f4OMiYnOwIrM1y8s/0dpQozL8XxRkhGYP9nlxwI5boKwdhWwRS0LTDoor1lR+DLhiNtc="
